{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMg9Q3RRfRbDqzIruqvsLPP",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Akshay15042002/Projects/blob/main/Titanic.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "1L9wSQP2ijRw",
        "outputId": "7583c9c9-6fe3-4030-8efc-cc87be3da520"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n",
            "Requirement already satisfied: pyforest in /usr/local/lib/python3.10/dist-packages (1.1.0)\n"
          ]
        }
      ],
      "source": [
        "!pip install pyforest\n",
        "import pyforest"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data=pd.read_csv(\"titanic.csv\")\n",
        "data.shape\n",
        "#data.isna()\n",
        "data.isna().sum()\n",
        "data.describe()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 344
        },
        "id": "MfQbuNGmjKS7",
        "outputId": "9b1a9a4c-3a23-45ed-a629-a29e7df41741"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "       PassengerId    Survived      Pclass  ...       SibSp       Parch        Fare\n",
              "count   891.000000  891.000000  891.000000  ...  891.000000  891.000000  891.000000\n",
              "mean    446.000000    0.383838    2.308642  ...    0.523008    0.381594   32.204208\n",
              "std     257.353842    0.486592    0.836071  ...    1.102743    0.806057   49.693429\n",
              "min       1.000000    0.000000    1.000000  ...    0.000000    0.000000    0.000000\n",
              "25%     223.500000    0.000000    2.000000  ...    0.000000    0.000000    7.910400\n",
              "50%     446.000000    0.000000    3.000000  ...    0.000000    0.000000   14.454200\n",
              "75%     668.500000    1.000000    3.000000  ...    1.000000    0.000000   31.000000\n",
              "max     891.000000    1.000000    3.000000  ...    8.000000    6.000000  512.329200\n",
              "\n",
              "[8 rows x 7 columns]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-09f8cfe1-2f0c-4f39-81fe-4af1614ac14f\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>PassengerId</th>\n",
              "      <th>Survived</th>\n",
              "      <th>Pclass</th>\n",
              "      <th>Age</th>\n",
              "      <th>SibSp</th>\n",
              "      <th>Parch</th>\n",
              "      <th>Fare</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>count</th>\n",
              "      <td>891.000000</td>\n",
              "      <td>891.000000</td>\n",
              "      <td>891.000000</td>\n",
              "      <td>714.000000</td>\n",
              "      <td>891.000000</td>\n",
              "      <td>891.000000</td>\n",
              "      <td>891.000000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>mean</th>\n",
              "      <td>446.000000</td>\n",
              "      <td>0.383838</td>\n",
              "      <td>2.308642</td>\n",
              "      <td>29.699118</td>\n",
              "      <td>0.523008</td>\n",
              "      <td>0.381594</td>\n",
              "      <td>32.204208</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>std</th>\n",
              "      <td>257.353842</td>\n",
              "      <td>0.486592</td>\n",
              "      <td>0.836071</td>\n",
              "      <td>14.526497</td>\n",
              "      <td>1.102743</td>\n",
              "      <td>0.806057</td>\n",
              "      <td>49.693429</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>min</th>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.420000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>25%</th>\n",
              "      <td>223.500000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>2.000000</td>\n",
              "      <td>20.125000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>7.910400</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>50%</th>\n",
              "      <td>446.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>3.000000</td>\n",
              "      <td>28.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>14.454200</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>75%</th>\n",
              "      <td>668.500000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>3.000000</td>\n",
              "      <td>38.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>31.000000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>max</th>\n",
              "      <td>891.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>3.000000</td>\n",
              "      <td>80.000000</td>\n",
              "      <td>8.000000</td>\n",
              "      <td>6.000000</td>\n",
              "      <td>512.329200</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-09f8cfe1-2f0c-4f39-81fe-4af1614ac14f')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-09f8cfe1-2f0c-4f39-81fe-4af1614ac14f button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-09f8cfe1-2f0c-4f39-81fe-4af1614ac14f');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ]
          },
          "metadata": {},
          "execution_count": 126
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data.info()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "tvjqtwQCk0MZ",
        "outputId": "1fd80d5c-f885-423e-e182-60ec702e83c3"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "<class 'pandas.core.frame.DataFrame'>\n",
            "RangeIndex: 891 entries, 0 to 890\n",
            "Data columns (total 12 columns):\n",
            " #   Column       Non-Null Count  Dtype  \n",
            "---  ------       --------------  -----  \n",
            " 0   PassengerId  891 non-null    int64  \n",
            " 1   Survived     891 non-null    int64  \n",
            " 2   Pclass       891 non-null    int64  \n",
            " 3   Name         891 non-null    object \n",
            " 4   Sex          891 non-null    object \n",
            " 5   Age          714 non-null    float64\n",
            " 6   SibSp        891 non-null    int64  \n",
            " 7   Parch        891 non-null    int64  \n",
            " 8   Ticket       891 non-null    object \n",
            " 9   Fare         891 non-null    float64\n",
            " 10  Cabin        204 non-null    object \n",
            " 11  Embarked     889 non-null    object \n",
            "dtypes: float64(2), int64(5), object(5)\n",
            "memory usage: 83.7+ KB\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from sklearn import preprocessing\n",
        "#a=preprocessing.LabelEncoder()\n",
        "data['Sex']=preprocessing.LabelEncoder().fit_transform(data['Sex'])\n",
        "data['Sex'].value_counts()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "rJapFAddk9VS",
        "outputId": "44e2936c-6a53-475e-e987-dfaca228d45f"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "1    577\n",
              "0    314\n",
              "Name: Sex, dtype: int64"
            ]
          },
          "metadata": {},
          "execution_count": 128
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data['Age'].median()\n",
        "data['Age']=data['Age'].fillna(value=28)\n",
        "data"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 991
        },
        "id": "wnRs2q7KxwWn",
        "outputId": "06eb758b-0b59-4356-e6b9-4935ca4bc2ad"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "     PassengerId  Survived  Pclass  ...     Fare  Cabin  Embarked\n",
              "0              1         0       3  ...   7.2500    NaN         S\n",
              "1              2         1       1  ...  71.2833    C85         C\n",
              "2              3         1       3  ...   7.9250    NaN         S\n",
              "3              4         1       1  ...  53.1000   C123         S\n",
              "4              5         0       3  ...   8.0500    NaN         S\n",
              "..           ...       ...     ...  ...      ...    ...       ...\n",
              "886          887         0       2  ...  13.0000    NaN         S\n",
              "887          888         1       1  ...  30.0000    B42         S\n",
              "888          889         0       3  ...  23.4500    NaN         S\n",
              "889          890         1       1  ...  30.0000   C148         C\n",
              "890          891         0       3  ...   7.7500    NaN         Q\n",
              "\n",
              "[891 rows x 12 columns]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-0622bf8a-38a3-4f53-8f80-5d38e1123a60\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>PassengerId</th>\n",
              "      <th>Survived</th>\n",
              "      <th>Pclass</th>\n",
              "      <th>Name</th>\n",
              "      <th>Sex</th>\n",
              "      <th>Age</th>\n",
              "      <th>SibSp</th>\n",
              "      <th>Parch</th>\n",
              "      <th>Ticket</th>\n",
              "      <th>Fare</th>\n",
              "      <th>Cabin</th>\n",
              "      <th>Embarked</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>Braund, Mr. Owen Harris</td>\n",
              "      <td>1</td>\n",
              "      <td>22.0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>A/5 21171</td>\n",
              "      <td>7.2500</td>\n",
              "      <td>NaN</td>\n",
              "      <td>S</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>2</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>Cumings, Mrs. John Bradley (Florence Briggs Th...</td>\n",
              "      <td>0</td>\n",
              "      <td>38.0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>PC 17599</td>\n",
              "      <td>71.2833</td>\n",
              "      <td>C85</td>\n",
              "      <td>C</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>3</td>\n",
              "      <td>Heikkinen, Miss. Laina</td>\n",
              "      <td>0</td>\n",
              "      <td>26.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>STON/O2. 3101282</td>\n",
              "      <td>7.9250</td>\n",
              "      <td>NaN</td>\n",
              "      <td>S</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>4</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>Futrelle, Mrs. Jacques Heath (Lily May Peel)</td>\n",
              "      <td>0</td>\n",
              "      <td>35.0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>113803</td>\n",
              "      <td>53.1000</td>\n",
              "      <td>C123</td>\n",
              "      <td>S</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>5</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>Allen, Mr. William Henry</td>\n",
              "      <td>1</td>\n",
              "      <td>35.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>373450</td>\n",
              "      <td>8.0500</td>\n",
              "      <td>NaN</td>\n",
              "      <td>S</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>886</th>\n",
              "      <td>887</td>\n",
              "      <td>0</td>\n",
              "      <td>2</td>\n",
              "      <td>Montvila, Rev. Juozas</td>\n",
              "      <td>1</td>\n",
              "      <td>27.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>211536</td>\n",
              "      <td>13.0000</td>\n",
              "      <td>NaN</td>\n",
              "      <td>S</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>887</th>\n",
              "      <td>888</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>Graham, Miss. Margaret Edith</td>\n",
              "      <td>0</td>\n",
              "      <td>19.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>112053</td>\n",
              "      <td>30.0000</td>\n",
              "      <td>B42</td>\n",
              "      <td>S</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>888</th>\n",
              "      <td>889</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>Johnston, Miss. Catherine Helen \"Carrie\"</td>\n",
              "      <td>0</td>\n",
              "      <td>28.0</td>\n",
              "      <td>1</td>\n",
              "      <td>2</td>\n",
              "      <td>W./C. 6607</td>\n",
              "      <td>23.4500</td>\n",
              "      <td>NaN</td>\n",
              "      <td>S</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>889</th>\n",
              "      <td>890</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>Behr, Mr. Karl Howell</td>\n",
              "      <td>1</td>\n",
              "      <td>26.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>111369</td>\n",
              "      <td>30.0000</td>\n",
              "      <td>C148</td>\n",
              "      <td>C</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>890</th>\n",
              "      <td>891</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>Dooley, Mr. Patrick</td>\n",
              "      <td>1</td>\n",
              "      <td>32.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>370376</td>\n",
              "      <td>7.7500</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Q</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>891 rows × 12 columns</p>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-0622bf8a-38a3-4f53-8f80-5d38e1123a60')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-0622bf8a-38a3-4f53-8f80-5d38e1123a60 button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-0622bf8a-38a3-4f53-8f80-5d38e1123a60');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ]
          },
          "metadata": {},
          "execution_count": 129
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data.isna().sum()\n",
        "data=data.drop(['Cabin','Name','Ticket'],axis=1)\n",
        "g=data.groupby('Survived')\n",
        "g['Embarked'].value_counts()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "4dzmZ9SazaAh",
        "outputId": "b8bf48fc-a58b-4529-bda5-e40327456766"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "Survived  Embarked\n",
              "0         S           427\n",
              "          C            75\n",
              "          Q            47\n",
              "1         S           217\n",
              "          C            93\n",
              "          Q            30\n",
              "Name: Embarked, dtype: int64"
            ]
          },
          "metadata": {},
          "execution_count": 130
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data['Embarked']=data['Embarked'].fillna(value='S')"
      ],
      "metadata": {
        "id": "mpTVge2AykKR"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "data['Embarked']=preprocessing.LabelEncoder().fit_transform(data['Embarked'])\n",
        "data['Embarked'].value_counts()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Zj_kx9130_Ic",
        "outputId": "e30e182f-1c89-4f1b-cd97-9382bfab0e41"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "2    646\n",
              "0    168\n",
              "1     77\n",
              "Name: Embarked, dtype: int64"
            ]
          },
          "metadata": {},
          "execution_count": 132
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "sns.countplot(x=data[\"Embarked\"],hue=data['Survived'])\n",
        "plt.show()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 449
        },
        "id": "_lXsvW9f1ioF",
        "outputId": "8c840c16-9107-498e-b152-ac88c695916f"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "\n",
              "        if (window._pyforest_update_imports_cell) { window._pyforest_update_imports_cell('import os\\nfrom sklearn import svm\\nimport skimage\\nimport fastai\\nfrom sklearn.model_selection import train_test_split\\nfrom sklearn import metrics\\nimport matplotlib.pyplot as plt\\nimport spacy\\nimport sklearn\\nimport pandas as pd\\nimport plotly as py\\nimport plotly.express as px\\nimport pydot\\nimport statistics\\nimport sys\\nimport pickle\\nimport seaborn as sns'); }\n",
              "    "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "\n",
              "        if (window._pyforest_update_imports_cell) { window._pyforest_update_imports_cell('import os\\nfrom sklearn import svm\\nimport skimage\\nimport fastai\\nfrom sklearn.model_selection import train_test_split\\nfrom sklearn import metrics\\nimport matplotlib.pyplot as plt\\nimport spacy\\nimport sklearn\\nimport pandas as pd\\nimport plotly as py\\nimport plotly.express as px\\nimport pydot\\nimport statistics\\nimport sys\\nimport pickle\\nimport seaborn as sns'); }\n",
              "    "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<Figure size 640x480 with 1 Axes>"
            ],
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAjsAAAGwCAYAAABPSaTdAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/bCgiHAAAACXBIWXMAAA9hAAAPYQGoP6dpAAAy+klEQVR4nO3de3RU9b3//9fkNiEkkzRAMklJKIIVUhLQoGGqX4oQCAEvlFhvORAtB09p0GJapGkRENR4a/EWwVohWIlS20ILrShGE1QSL9EIAlKh8QQXmQTRZCCYC8n8/vCwf46AYm572Dwfa+21sj/7sz/7vcdx8VqffRmb1+v1CgAAwKICzC4AAACgJxF2AACApRF2AACApRF2AACApRF2AACApRF2AACApRF2AACApQWZXYA/6Ojo0IEDBxQRESGbzWZ2OQAA4DR4vV4dPnxY8fHxCgg49fwNYUfSgQMHlJCQYHYZAACgE/bv36+BAweecjthR1JERISkLz4sh8NhcjUAAOB0eDweJSQkGP+OnwphRzIuXTkcDsIOAABnmG+6BYUblAEAgKURdgAAgKURdgAAgKVxzw4AAH6go6NDra2tZpfhV4KDgxUYGNjlcQg7AACYrLW1VdXV1ero6DC7FL8TFRUlp9PZpffgEXYAADCR1+tVbW2tAgMDlZCQ8LUvxzubeL1eHT16VPX19ZKkuLi4To9F2AEAwETHjh3T0aNHFR8fr7CwMLPL8St9+vSRJNXX1ysmJqbTl7SIjwAAmKi9vV2SFBISYnIl/ul4AGxra+v0GIQdAAD8AL/NeHLd8bkQdgAAgKURdgAAgKURdgAAwAlKS0tls9nU0NDQo8e54YYbNG3atB49BmEHAAA/dvDgQc2ZM0eJiYmy2+1yOp3KyMjQ66+/3qPH/eEPf6ja2lpFRkb26HF6A4+eAwDgx7KystTa2qo1a9bonHPOUV1dnUpKSnTo0KFOjef1etXe3q6goK+PACEhIXI6nZ06hr9hZgcAAD/V0NCgV199Vffee68uvfRSDRo0SBdddJHy8/N1xRVX6KOPPpLNZlNVVZXPPjabTaWlpZL+/8tRzz//vFJTU2W327Vq1SrZbDZ98MEHPsdbvny5hgwZ4rNfQ0ODPB6P+vTpo+eff96n//r16xUREaGjR49Kkvbv36+rr75aUVFRio6O1pVXXqmPPvrI6N/e3q68vDxFRUWpX79+uu222+T1erv/g/sKZnYAAL0mdf5TZpfgFyrvn3la/cLDwxUeHq4NGzZozJgxstvtnT7mr3/9az3wwAM655xz9J3vfEdPPPGE1q5dq2XLlhl91q5dq+uvv/6EfR0Ohy677DIVFxcrMzPTp/+0adMUFhamtrY2ZWRkyOVy6dVXX1VQUJDuvPNOTZ48Wdu3b1dISIh+97vfqaioSKtWrdLw4cP1u9/9TuvXr9f48eM7fV6ng5kdAAD8VFBQkIqKirRmzRpFRUXp4osv1m9+8xtt3779W4+1dOlSTZw4UUOGDFF0dLSys7P1zDPPGNv//e9/q7KyUtnZ2SfdPzs7Wxs2bDBmcTwej/75z38a/detW6eOjg798Y9/VHJysoYPH67Vq1erpqbGmGV68MEHlZ+fr+nTp2v48OFauXJlr9wTRNgBAMCPZWVl6cCBA/rHP/6hyZMnq7S0VBdccIGKioq+1TijR4/2Wb/22mv10UcfqaKiQtIXszQXXHCBhg0bdtL9p0yZouDgYP3jH/+QJP31r3+Vw+FQenq6JOm9997T3r17FRERYcxIRUdHq7m5Wfv27VNjY6Nqa2uVlpZmjBkUFHRCXT2BsAMAgJ8LDQ3VxIkTdfvtt2vbtm264YYbtHjxYuNHQ79838upflahb9++PutOp1Pjx49XcXGxJKm4uPiUszrSFzcsX3XVVT79r7nmGuNG5yNHjig1NVVVVVU+y7///e+TXhrrTYQdAADOMElJSWpqatKAAQMkSbW1tca2L9+s/E2ys7O1bt06lZeX6z//+Y+uvfbab+y/efNm7dy5Uy+//LJPOLrgggv04YcfKiYmRkOHDvVZIiMjFRkZqbi4OL3xxhvGPseOHVNlZeVp19tZhB0AAPzUoUOHNH78eD399NPavn27qqur9dxzz+m+++7TlVdeqT59+mjMmDG65557tHv3bpWVlWnhwoWnPf706dN1+PBhzZkzR5deeqni4+O/tv/YsWPldDqVnZ2twYMH+1ySys7OVv/+/XXllVfq1VdfVXV1tUpLS3XLLbfo448/liT94he/0D333KMNGzbogw8+0M9//vMef2mhRNgBAMBvhYeHKy0tTcuXL9fYsWM1YsQI3X777Zo9e7YeffRRSdKqVat07Ngxpaamat68ebrzzjtPe/yIiAhdfvnleu+99772EtZxNptN11133Un7h4WFaevWrUpMTDRuQJ41a5aam5vlcDgkSb/85S81Y8YM5eTkyOVyKSIiQj/+8Y+/xSfSOTZvbzzg7uc8Ho8iIyPV2Nho/AcBAHQ/Hj3/wpcfPW9ublZ1dbUGDx6s0NBQE6vyT1/3+Zzuv9/M7AAAAEsj7AAAAEsj7AAAAEsj7AAAAEsj7AAAAEsj7AAAAEsj7AAAAEsj7AAAAEsj7AAAAEsLMrsAAADw7fT2m6i//Mbnb6OwsFD333+/3G63Ro4cqUceeUQXXXRRN1f3zfxmZueee+6RzWbTvHnzjLbm5mbl5uaqX79+Cg8PV1ZWlurq6nz2q6mp0dSpUxUWFqaYmBjNnz9fx44d6+XqAQDAl61bt055eXlavHix3nnnHY0cOVIZGRmqr6/v9Vr8Iuy89dZbevzxx5WSkuLTfuutt2rjxo167rnnVFZWpgMHDmj69OnG9vb2dk2dOlWtra3atm2b1qxZo6KiIi1atKi3TwEAAHzJ73//e82ePVs33nijkpKStHLlSoWFhWnVqlW9XovpYefIkSPKzs7WE088oe985ztGe2Njo5588kn9/ve/1/jx45WamqrVq1dr27ZtqqiokCS9+OKL2rVrl55++mmNGjVKmZmZWrZsmQoLC9Xa2mrWKQEAcFZrbW1VZWWl0tPTjbaAgAClp6ervLy81+sxPezk5uZq6tSpPh+IJFVWVqqtrc2nfdiwYUpMTDQ+qPLyciUnJys2Ntbok5GRIY/Ho507d57ymC0tLfJ4PD4LAADoHp988ona29t9/n2WpNjYWLnd7l6vx9QblJ999lm98847euutt07Y5na7FRISoqioKJ/2L39Qbrf7pB/k8W2nUlBQoDvuuKOL1QMAgDOBaTM7+/fv1y9+8QutXbtWoaGhvXrs/Px8NTY2Gsv+/ft79fgAAFhZ//79FRgYeMJDRXV1dXI6nb1ej2lhp7KyUvX19brgggsUFBSkoKAglZWV6eGHH1ZQUJBiY2PV2tqqhoYGn/2+/EE5nc6TfpDHt52K3W6Xw+HwWQAAQPcICQlRamqqSkpKjLaOjg6VlJTI5XL1ej2mhZ0JEyZox44dqqqqMpbRo0crOzvb+Ds4ONjng9qzZ49qamqMD8rlcmnHjh0+j7Ft2bJFDodDSUlJvX5OAADgC3l5eXriiSe0Zs0a7d69W3PmzFFTU5NuvPHGXq/FtHt2IiIiNGLECJ+2vn37ql+/fkb7rFmzlJeXp+joaDkcDt18881yuVwaM2aMJGnSpElKSkrSjBkzdN9998ntdmvhwoXKzc2V3W7v9XMCAABfuOaaa3Tw4EEtWrRIbrdbo0aN0ubNm0+417Y3+PUblJcvX66AgABlZWWppaVFGRkZeuyxx4ztgYGB2rRpk+bMmSOXy6W+ffsqJydHS5cuNbFqAAB6VmffaNzb5s6dq7lz55pdhn+FndLSUp/10NBQFRYWqrCw8JT7DBo0SP/61796uDIAAHCmMv09OwAAAD2JsAMAACyNsAMAACyNsAMAACyNsAMAACyNsAMAACyNsAMAACyNsAMAACyNsAMAACzNr96gDAAAvlnN0uRePV7ioh3fqv/WrVt1//33q7KyUrW1tVq/fr2mTZvWM8WdBmZ2AABAt2pqatLIkSO/9ueeehMzOwAAoFtlZmYqMzPT7DIMzOwAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABL42ksAADQrY4cOaK9e/ca69XV1aqqqlJ0dLQSExN7vR7CDgAA6FZvv/22Lr30UmM9Ly9PkpSTk6OioqJer4ewAwDAGebbvtG4t40bN05er9fsMgzcswMAACyNsAMAACyNsAMAACyNsAMAACyNsAMAgB/wpxt6/Ul3fC6EHQAATBQYGChJam1tNbkS/3T06FFJUnBwcKfH4NFzAABMFBQUpLCwMB08eFDBwcEKCGAeQvpiRufo0aOqr69XVFSUEQo7g7ADAICJbDab4uLiVF1drf/93/81uxy/ExUVJafT2aUxCDsAAJgsJCRE5557LpeyviI4OLhLMzrHEXYAAPADAQEBCg0NNbsMS+LCIAAAsDRTw86KFSuUkpIih8Mhh8Mhl8ul559/3tg+btw42Ww2n+VnP/uZzxg1NTWaOnWqwsLCFBMTo/nz5+vYsWO9fSoAAMBPmXoZa+DAgbrnnnt07rnnyuv1as2aNbryyiv17rvv6gc/+IEkafbs2Vq6dKmxT1hYmPF3e3u7pk6dKqfTqW3btqm2tlYzZ85UcHCw7r777l4/HwAA4H9MDTuXX365z/pdd92lFStWqKKiwgg7YWFhp7wL+8UXX9SuXbv00ksvKTY2VqNGjdKyZcu0YMECLVmyRCEhISfdr6WlRS0tLca6x+PppjMCAAD+xm/u2Wlvb9ezzz6rpqYmuVwuo33t2rXq37+/RowYofz8fOPlQpJUXl6u5ORkxcbGGm0ZGRnyeDzauXPnKY9VUFCgyMhIY0lISOiZkwIAAKYz/WmsHTt2yOVyqbm5WeHh4Vq/fr2SkpIkSddff70GDRqk+Ph4bd++XQsWLNCePXv0t7/9TZLkdrt9go4kY93tdp/ymPn5+crLyzPWPR4PgQcAAIsyPeycd955qqqqUmNjo/7yl78oJydHZWVlSkpK0k033WT0S05OVlxcnCZMmKB9+/ZpyJAhnT6m3W6X3W7vjvIBAICfM/0yVkhIiIYOHarU1FQVFBRo5MiReuihh07aNy0tTZK0d+9eSZLT6VRdXZ1Pn+PrXX3bIgAAsAbTw85XdXR0+Nw8/GVVVVWSpLi4OEmSy+XSjh07VF9fb/TZsmWLHA6HcSkMAACc3Uy9jJWfn6/MzEwlJibq8OHDKi4uVmlpqV544QXt27dPxcXFmjJlivr166ft27fr1ltv1dixY5WSkiJJmjRpkpKSkjRjxgzdd999crvdWrhwoXJzc7lMBQAAJJkcdurr6zVz5kzV1tYqMjJSKSkpeuGFFzRx4kTt379fL730kh588EE1NTUpISFBWVlZWrhwobF/YGCgNm3apDlz5sjlcqlv377KycnxeS8PAAA4u9m8Xq/X7CLM5vF4FBkZqcbGRjkcDrPLAQDLSp3/lNkl+IXK+2eaXYIlnO6/3353zw4AAEB3IuwAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLI+wAAABLMzXsrFixQikpKXI4HHI4HHK5XHr++eeN7c3NzcrNzVW/fv0UHh6urKws1dXV+YxRU1OjqVOnKiwsTDExMZo/f76OHTvW26cCAAD8lKlhZ+DAgbrnnntUWVmpt99+W+PHj9eVV16pnTt3SpJuvfVWbdy4Uc8995zKysp04MABTZ8+3di/vb1dU6dOVWtrq7Zt26Y1a9aoqKhIixYtMuuUAACAn7F5vV6v2UV8WXR0tO6//35dddVVGjBggIqLi3XVVVdJkj744AMNHz5c5eXlGjNmjJ5//nlddtllOnDggGJjYyVJK1eu1IIFC3Tw4EGFhISc9BgtLS1qaWkx1j0ejxISEtTY2CiHw9HzJwkAZ6nU+U+ZXYJfqLx/ptklWILH41FkZOQ3/vvtN/fstLe369lnn1VTU5NcLpcqKyvV1tam9PR0o8+wYcOUmJio8vJySVJ5ebmSk5ONoCNJGRkZ8ng8xuzQyRQUFCgyMtJYEhISeu7EAACAqUwPOzt27FB4eLjsdrt+9rOfaf369UpKSpLb7VZISIiioqJ8+sfGxsrtdkuS3G63T9A5vv34tlPJz89XY2Ojsezfv797TwoAAPiNILMLOO+881RVVaXGxkb95S9/UU5OjsrKynr0mHa7XXa7vUePAQAA/IPpYSckJERDhw6VJKWmpuqtt97SQw89pGuuuUatra1qaGjwmd2pq6uT0+mUJDmdTr355ps+4x1/Wut4HwAAcHYz/TLWV3V0dKilpUWpqakKDg5WSUmJsW3Pnj2qqamRy+WSJLlcLu3YsUP19fVGny1btsjhcCgpKanXawcAAP7H1Jmd/Px8ZWZmKjExUYcPH1ZxcbFKS0v1wgsvKDIyUrNmzVJeXp6io6PlcDh08803y+VyacyYMZKkSZMmKSkpSTNmzNB9990nt9uthQsXKjc3l8tUAABAkslhp76+XjNnzlRtba0iIyOVkpKiF154QRMnTpQkLV++XAEBAcrKylJLS4syMjL02GOPGfsHBgZq06ZNmjNnjlwul/r27aucnBwtXbrUrFMCAAB+xu/es2OG031OHwDQNbxn5wu8Z6d7nHHv2QEAAOgJhB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBphB0AAGBppoadgoICXXjhhYqIiFBMTIymTZumPXv2+PQZN26cbDabz/Kzn/3Mp09NTY2mTp2qsLAwxcTEaP78+Tp27FhvngoAAPBTQWYevKysTLm5ubrwwgt17Ngx/eY3v9GkSZO0a9cu9e3b1+g3e/ZsLV261FgPCwsz/m5vb9fUqVPldDq1bds21dbWaubMmQoODtbdd9/dq+cDAAD8j6lhZ/PmzT7rRUVFiomJUWVlpcaOHWu0h4WFyel0nnSMF198Ubt27dJLL72k2NhYjRo1SsuWLdOCBQu0ZMkShYSE9Og5AAAA/+ZX9+w0NjZKkqKjo33a165dq/79+2vEiBHKz8/X0aNHjW3l5eVKTk5WbGys0ZaRkSGPx6OdO3ee9DgtLS3yeDw+CwAAsCZTZ3a+rKOjQ/PmzdPFF1+sESNGGO3XX3+9Bg0apPj4eG3fvl0LFizQnj179Le//U2S5Ha7fYKOJGPd7Xaf9FgFBQW64447euhMAACAP/GbsJObm6v3339fr732mk/7TTfdZPydnJysuLg4TZgwQfv27dOQIUM6daz8/Hzl5eUZ6x6PRwkJCZ0rHAAA+DW/uIw1d+5cbdq0Sa+88ooGDhz4tX3T0tIkSXv37pUkOZ1O1dXV+fQ5vn6q+3zsdrscDofPAgAArMnUsOP1ejV37lytX79eL7/8sgYPHvyN+1RVVUmS4uLiJEkul0s7duxQfX290WfLli1yOBxKSkrqkboBAMCZo1NhZ/z48WpoaDih3ePxaPz48ac9Tm5urp5++mkVFxcrIiJCbrdbbrdbn3/+uSRp3759WrZsmSorK/XRRx/pH//4h2bOnKmxY8cqJSVFkjRp0iQlJSVpxowZeu+99/TCCy9o4cKFys3Nld1u78zpAQAAC+lU2CktLVVra+sJ7c3NzXr11VdPe5wVK1aosbFR48aNU1xcnLGsW7dOkhQSEqKXXnpJkyZN0rBhw/TLX/5SWVlZ2rhxozFGYGCgNm3apMDAQLlcLv3Xf/2XZs6c6fNeHgAAcPb6Vjcob9++3fh7165dPk87tbe3a/Pmzfrud7972uN5vd6v3Z6QkKCysrJvHGfQoEH617/+ddrHBQAAZ49vFXZGjRpl/GTDyS5X9enTR4888ki3FQcAANBV3yrsVFdXy+v16pxzztGbb76pAQMGGNtCQkIUExOjwMDAbi8SAACgs75V2Bk0aJCkL14ACAAAcCbo9EsFP/zwQ73yyiuqr68/IfwsWrSoy4UBAAB0h06FnSeeeEJz5sxR//795XQ6ZbPZjG02m42wAwAA/Eanws6dd96pu+66SwsWLOjuegAAALpVp96z89lnn+knP/lJd9cCAADQ7ToVdn7yk5/oxRdf7O5aAAAAul2nLmMNHTpUt99+uyoqKpScnKzg4GCf7bfccku3FAcAANBVnQo7f/jDHxQeHq6ysrIT3nBss9kIOwAAwG90KuxUV1d3dx0AAAA9olP37AAAAJwpOjWz89Of/vRrt69atapTxQAAAHS3ToWdzz77zGe9ra1N77//vhoaGk76A6EAAABm6VTYWb9+/QltHR0dmjNnjoYMGdLlogAAALpLt92zExAQoLy8PC1fvry7hgQAAOiybr1Bed++fTp27Fh3DgkAANAlnbqMlZeX57Pu9XpVW1urf/7zn8rJyemWwgAAALpDp8LOu+++67MeEBCgAQMG6He/+903PqkFAMDZrmZpstkl+IXERTt65TidCjuvvPJKd9cBAADQIzoVdo47ePCg9uzZI0k677zzNGDAgG4pCgAAoLt06gblpqYm/fSnP1VcXJzGjh2rsWPHKj4+XrNmzdLRo0e7u0YAAIBO61TYycvLU1lZmTZu3KiGhgY1NDTo73//u8rKyvTLX/6yu2sEAADotE5dxvrrX/+qv/zlLxo3bpzRNmXKFPXp00dXX321VqxY0V31AQAAdEmnZnaOHj2q2NjYE9pjYmK4jAUAAPxKp8KOy+XS4sWL1dzcbLR9/vnnuuOOO+RyubqtOAAAgK7q1GWsBx98UJMnT9bAgQM1cuRISdJ7770nu92uF198sVsLBAAA6IpOhZ3k5GR9+OGHWrt2rT744ANJ0nXXXafs7Gz16dOnWwsEAADoik6FnYKCAsXGxmr27Nk+7atWrdLBgwe1YMGCbikOAACgqzp1z87jjz+uYcOGndD+gx/8QCtXruxyUQAAAN2lU2HH7XYrLi7uhPYBAwaotrb2tMcpKCjQhRdeqIiICMXExGjatGnGG5mPa25uVm5urvr166fw8HBlZWWprq7Op09NTY2mTp2qsLAwxcTEaP78+fz6OgAAkNTJsJOQkKDXX3/9hPbXX39d8fHxpz1OWVmZcnNzVVFRoS1btqitrU2TJk1SU1OT0efWW2/Vxo0b9dxzz6msrEwHDhzQ9OnTje3t7e2aOnWqWltbtW3bNq1Zs0ZFRUVatGhRZ04NAABYTKfu2Zk9e7bmzZuntrY2jR8/XpJUUlKi22677Vu9QXnz5s0+60VFRYqJiVFlZaXGjh2rxsZGPfnkkyouLjaOs3r1ag0fPlwVFRUaM2aMXnzxRe3atUsvvfSSYmNjNWrUKC1btkwLFizQkiVLFBIS0plTBAAAFtGpsDN//nwdOnRIP//5z9Xa2ipJCg0N1YIFC5Sfn9/pYhobGyVJ0dHRkqTKykq1tbUpPT3d6DNs2DAlJiaqvLxcY8aMUXl5uZKTk31ecpiRkaE5c+Zo586dOv/88084TktLi1paWox1j8fT6ZoBAIB/69RlLJvNpnvvvVcHDx5URUWF3nvvPX366addunTU0dGhefPm6eKLL9aIESMkfXFvUEhIiKKionz6xsbGyu12G32++jbn4+vH+3xVQUGBIiMjjSUhIaHTdQMAAP/WqbBzXHh4uC688EKNGDFCdru9S4Xk5ubq/fff17PPPtulcU5Hfn6+GhsbjWX//v09fkwAAGCOTl3G6m5z587Vpk2btHXrVg0cONBodzqdam1tVUNDg8/sTl1dnZxOp9HnzTff9Bnv+NNax/t8ld1u73I4AwAAZ4Yuzex0ldfr1dy5c7V+/Xq9/PLLGjx4sM/21NRUBQcHq6SkxGjbs2ePampqjN/gcrlc2rFjh+rr640+W7ZskcPhUFJSUu+cCAAA8Fumzuzk5uaquLhYf//73xUREWHcYxMZGak+ffooMjJSs2bNUl5enqKjo+VwOHTzzTfL5XJpzJgxkqRJkyYpKSlJM2bM0H333Se3262FCxcqNzeX2RsAAGBu2FmxYoUkady4cT7tq1ev1g033CBJWr58uQICApSVlaWWlhZlZGToscceM/oGBgZq06ZNmjNnjlwul/r27aucnBwtXbq0t04DAAD4MVPDjtfr/cY+oaGhKiwsVGFh4Sn7DBo0SP/617+6szQAAGARpt6zAwAA0NMIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNIIOwAAwNJMDTtbt27V5Zdfrvj4eNlsNm3YsMFn+w033CCbzeazTJ482afPp59+quzsbDkcDkVFRWnWrFk6cuRIL54FAADwZ6aGnaamJo0cOVKFhYWn7DN58mTV1tYayzPPPOOzPTs7Wzt37tSWLVu0adMmbd26VTfddFNPlw4AAM4QQWYePDMzU5mZmV/bx263y+l0nnTb7t27tXnzZr311lsaPXq0JOmRRx7RlClT9MADDyg+Pr7bawYAAGcWv79np7S0VDExMTrvvPM0Z84cHTp0yNhWXl6uqKgoI+hIUnp6ugICAvTGG2+ccsyWlhZ5PB6fBQAAWJNfh53JkyfrqaeeUklJie69916VlZUpMzNT7e3tkiS3262YmBiffYKCghQdHS23233KcQsKChQZGWksCQkJPXoeAADAPKZexvom1157rfF3cnKyUlJSNGTIEJWWlmrChAmdHjc/P195eXnGusfjIfAAAGBRfj2z81XnnHOO+vfvr71790qSnE6n6uvrffocO3ZMn3766Snv85G+uA/I4XD4LAAAwJrOqLDz8ccf69ChQ4qLi5MkuVwuNTQ0qLKy0ujz8ssvq6OjQ2lpaWaVCQAA/Iipl7GOHDlizNJIUnV1taqqqhQdHa3o6GjdcccdysrKktPp1L59+3Tbbbdp6NChysjIkCQNHz5ckydP1uzZs7Vy5Uq1tbVp7ty5uvbaa3kSCwAASDJ5Zuftt9/W+eefr/PPP1+SlJeXp/PPP1+LFi1SYGCgtm/friuuuELf//73NWvWLKWmpurVV1+V3W43xli7dq2GDRumCRMmaMqUKbrkkkv0hz/8waxTAgAAfsbUmZ1x48bJ6/WecvsLL7zwjWNER0eruLi4O8sCAAAWckbdswMAAPBtEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClEXYAAIClmRp2tm7dqssvv1zx8fGy2WzasGGDz3av16tFixYpLi5Offr0UXp6uj788EOfPp9++qmys7PlcDgUFRWlWbNm6ciRI714FgAAwJ+ZGnaampo0cuRIFRYWnnT7fffdp4cfflgrV67UG2+8ob59+yojI0PNzc1Gn+zsbO3cuVNbtmzRpk2btHXrVt100029dQoAAMDPBZl58MzMTGVmZp50m9fr1YMPPqiFCxfqyiuvlCQ99dRTio2N1YYNG3Tttddq9+7d2rx5s9566y2NHj1akvTII49oypQpeuCBBxQfH3/SsVtaWtTS0mKsezyebj4zAADgL/z2np3q6mq53W6lp6cbbZGRkUpLS1N5ebkkqby8XFFRUUbQkaT09HQFBATojTfeOOXYBQUFioyMNJaEhISeOxEAAGAqvw07brdbkhQbG+vTHhsba2xzu92KiYnx2R4UFKTo6Gijz8nk5+ersbHRWPbv39/N1QMAAH9h6mUss9jtdtntdrPLAAAAvcBvZ3acTqckqa6uzqe9rq7O2OZ0OlVfX++z/dixY/r000+NPgAA4Ozmt2Fn8ODBcjqdKikpMdo8Ho/eeOMNuVwuSZLL5VJDQ4MqKyuNPi+//LI6OjqUlpbW6zUDAAD/Y+plrCNHjmjv3r3GenV1taqqqhQdHa3ExETNmzdPd955p84991wNHjxYt99+u+Lj4zVt2jRJ0vDhwzV58mTNnj1bK1euVFtbm+bOnatrr732lE9iAQCAs4upYeftt9/WpZdeaqzn5eVJknJyclRUVKTbbrtNTU1Nuummm9TQ0KBLLrlEmzdvVmhoqLHP2rVrNXfuXE2YMEEBAQHKysrSww8/3Ovngi/ULE02uwS/kLhoh9klAAD+j6lhZ9y4cfJ6vafcbrPZtHTpUi1duvSUfaKjo1VcXNwT5QEAAAvw23t2AAAAugNhBwAAWBphBwAAWBphBwAAWBphBwAAWBphBwAAWBphBwAAWBphBwAAWBphBwAAWBphBwAAWBphBwAAWBphBwAAWBphBwAAWJqpv3puJanznzK7BL+wPsLsCgAA8MXMDgAAsDTCDgAAsDTCDgAAsDTCDgAAsDTCDgAAsDTCDgAAsDTCDgAAsDTCDgAAsDTCDgAAsDTCDgAAsDTCDgAAsDTCDgAAsDTCDgAAsDTCDgAAsDTCDgAAsDTCDgAAsDS/DjtLliyRzWbzWYYNG2Zsb25uVm5urvr166fw8HBlZWWprq7OxIoBAIC/8euwI0k/+MEPVFtbayyvvfaase3WW2/Vxo0b9dxzz6msrEwHDhzQ9OnTTawWAAD4myCzC/gmQUFBcjqdJ7Q3NjbqySefVHFxscaPHy9JWr16tYYPH66KigqNGTOmt0sFAAB+yO9ndj788EPFx8frnHPOUXZ2tmpqaiRJlZWVamtrU3p6utF32LBhSkxMVHl5+deO2dLSIo/H47MAAABr8uuwk5aWpqKiIm3evFkrVqxQdXW1/t//+386fPiw3G63QkJCFBUV5bNPbGys3G73145bUFCgyMhIY0lISOjBswAAAGby68tYmZmZxt8pKSlKS0vToEGD9Oc//1l9+vTp9Lj5+fnKy8sz1j0eD4EHAACL8uuw81VRUVH6/ve/r71792rixIlqbW1VQ0ODz+xOXV3dSe/x+TK73S673d7D1QLmS53/lNkl+IXK+2eaXQIAE/n1ZayvOnLkiPbt26e4uDilpqYqODhYJSUlxvY9e/aopqZGLpfLxCoBAIA/8euZnV/96le6/PLLNWjQIB04cECLFy9WYGCgrrvuOkVGRmrWrFnKy8tTdHS0HA6Hbr75ZrlcLp7EAgAABr8OOx9//LGuu+46HTp0SAMGDNAll1yiiooKDRgwQJK0fPlyBQQEKCsrSy0tLcrIyNBjjz1mctUAAMCf+HXYefbZZ792e2hoqAoLC1VYWNhLFQEAgDPNGXXPDgAAwLdF2AEAAJZG2AEAAJZG2AEAAJZG2AEAAJZG2AEAAJZG2AEAAJZG2AEAAJZG2AEAAJbm129QBoDuULM02ewS/ELioh1mlwCYgpkdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaYQdAABgaZYJO4WFhfre976n0NBQpaWl6c033zS7JAAA4AcsEXbWrVunvLw8LV68WO+8845GjhypjIwM1dfXm10aAAAwmSXCzu9//3vNnj1bN954o5KSkrRy5UqFhYVp1apVZpcGAABMFmR2AV3V2tqqyspK5efnG20BAQFKT09XeXn5SfdpaWlRS0uLsd7Y2ChJ8ng8na6jveXzTu9rJYeD280uwS905bvUnfhefoHv5Rf84XvJd/ILfCe/0NXv5PH9vV7v1/Y748POJ598ovb2dsXGxvq0x8bG6oMPPjjpPgUFBbrjjjtOaE9ISOiRGs8mI8wuwF8URJpdAb6E7+X/4XvpN/hO/p9u+k4ePnxYkZGnHuuMDzudkZ+fr7y8PGO9o6NDn376qfr16yebzWZiZWc2j8ejhIQE7d+/Xw6Hw+xyAEl8L+F/+E52H6/Xq8OHDys+Pv5r+53xYad///4KDAxUXV2dT3tdXZ2cTudJ97Hb7bLb7T5tUVFRPVXiWcfhcPA/MPwO30v4G76T3ePrZnSOO+NvUA4JCVFqaqpKSkqMto6ODpWUlMjlcplYGQAA8Adn/MyOJOXl5SknJ0ejR4/WRRddpAcffFBNTU268cYbzS4NAACYzBJh55prrtHBgwe1aNEiud1ujRo1Sps3bz7hpmX0LLvdrsWLF59wiRAwE99L+Bu+k73P5v2m57UAAADOYGf8PTsAAABfh7ADAAAsjbADAAAsjbADAAAsjbCDblNYWKjvfe97Cg0NVVpamt58802zS8JZbOvWrbr88ssVHx8vm82mDRs2mF0SznIFBQW68MILFRERoZiYGE2bNk179uwxu6yzAmEH3WLdunXKy8vT4sWL9c4772jkyJHKyMhQfX292aXhLNXU1KSRI0eqsLDQ7FIASVJZWZlyc3NVUVGhLVu2qK2tTZMmTVJTU5PZpVkej56jW6SlpenCCy/Uo48+KumLt1gnJCTo5ptv1q9//WuTq8PZzmazaf369Zo2bZrZpQCGgwcPKiYmRmVlZRo7dqzZ5VgaMzvostbWVlVWVio9Pd1oCwgIUHp6usrLy02sDAD8V2NjoyQpOjra5Eqsj7CDLvvkk0/U3t5+whurY2Nj5Xa7TaoKAPxXR0eH5s2bp4svvlgjRowwuxzLs8TPRQAAcCbJzc3V+++/r9dee83sUs4KhB10Wf/+/RUYGKi6ujqf9rq6OjmdTpOqAgD/NHfuXG3atElbt27VwIEDzS7nrMBlLHRZSEiIUlNTVVJSYrR1dHSopKRELpfLxMoAwH94vV7NnTtX69ev18svv6zBgwebXdJZg5kddIu8vDzl5ORo9OjRuuiii/Tggw+qqalJN954o9ml4Sx15MgR7d2711ivrq5WVVWVoqOjlZiYaGJlOFvl5uaquLhYf//73xUREWHc0xgZGak+ffqYXJ218eg5us2jjz6q+++/X263W6NGjdLDDz+stLQ0s8vCWaq0tFSXXnrpCe05OTkqKirq/YJw1rPZbCdtX716tW644YbeLeYsQ9gBAACWxj07AADA0gg7AADA0gg7AADA0gg7AADA0gg7AADA0gg7AADA0gg7AADA0gg7AADA0gg7AM4oS5Ys0ahRo3pk7NLSUtlsNjU0NHTbmB999JFsNpuqqqq6bUwA3w5hB0CPueGGG2Sz2U5YJk+ebHZpAM4i/BAogB41efJkrV692qfNbrebVM2ptbW1mV0CgB7CzA6AHmW32+V0On2W73znO5K++GHExx9/XJdddpnCwsI0fPhwlZeXa+/evRo3bpz69u2rH/7wh9q3b98J4z7++ONKSEhQWFiYrr76ajU2Nhrb3nrrLU2cOFH9+/dXZGSkfvSjH+mdd97x2d9ms2nFihW64oor1LdvX911110nHOPo0aPKzMzUxRdfbFza+uMf/6jhw4crNDRUw4YN02OPPeazz5tvvqnzzz9foaGhGj16tN59992ufoQAuoiwA8BUy5Yt08yZM1VVVaVhw4bp+uuv1//8z/8oPz9fb7/9trxer+bOneuzz969e/XnP/9ZGzdu1ObNm/Xuu+/q5z//ubH98OHDysnJ0WuvvaaKigqde+65mjJlig4fPuwzzpIlS/TjH/9YO3bs0E9/+lOfbQ0NDZo4caI6Ojq0ZcsWRUVFae3atVq0aJHuuusu7d69W3fffbduv/12rVmzRpJ05MgRXXbZZUpKSlJlZaWWLFmiX/3qVz30yQE4bV4A6CE5OTnewMBAb9++fX2Wu+66y+v1er2SvAsXLjT6l5eXeyV5n3zySaPtmWee8YaGhhrrixcv9gYGBno//vhjo+3555/3BgQEeGtra09aR3t7uzciIsK7ceNGo02Sd968eT79XnnlFa8k7+7du70pKSnerKwsb0tLi7F9yJAh3uLiYp99li1b5nW5XF6v1+t9/PHHvf369fN+/vnnxvYVK1Z4JXnffffdb/y8APQM7tkB0KMuvfRSrVixwqctOjra+DslJcX4OzY2VpKUnJzs09bc3CyPxyOHwyFJSkxM1He/+12jj8vlUkdHh/bs2SOn06m6ujotXLhQpaWlqq+vV3t7u44ePaqamhqfOkaPHn3SmidOnKiLLrpI69atU2BgoCSpqalJ+/bt06xZszR79myj77FjxxQZGSlJ2r17t1JSUhQaGupTGwBzEXYA9Ki+fftq6NChp9weHBxs/G2z2U7Z1tHRcdrHzMnJ0aFDh/TQQw9p0KBBstvtcrlcam1tPaG2k5k6dar++te/ateuXUbwOnLkiCTpiSeeUFpamk//44EIgH8i7AA449TU1OjAgQOKj4+XJFVUVCggIEDnnXeeJOn111/XY489pilTpkiS9u/fr08++eS0x7/nnnsUHh6uCRMmqLS0VElJSYqNjVV8fLz+85//KDs7+6T7DR8+XH/605/U3NxszO5UVFR05VQBdAPCDoAe1dLSIrfb7dMWFBSk/v37d3rM0NBQ5eTk6IEHHpDH49Ett9yiq6++Wk6nU5J07rnn6k9/+pNGjx4tj8ej+fPnq0+fPt/qGA888IDa29s1fvx4lZaWatiwYbrjjjt0yy23KDIyUpMnT1ZLS4vefvttffbZZ8rLy9P111+v3/72t5o9e7by8/P10Ucf6YEHHuj0eQLoHjyNBaBHbd68WXFxcT7LJZdc0qUxhw4dqunTp2vKlCmaNGmSUlJSfB4Bf/LJJ/XZZ5/pggsu0IwZM3TLLbcoJibmWx9n+fLluvrqqzV+/Hj9+9//1n//93/rj3/8o1avXq3k5GT96Ec/UlFRkQYPHixJCg8P18aNG7Vjxw6df/75+u1vf6t77723S+cKoOtsXq/Xa3YRAAAAPYWZHQAAYGmEHQAAYGmEHQAAYGmEHQAAYGmEHQAAYGmEHQAAYGmEHQAAYGmEHQAAYGmEHQAAYGmEHQAAYGmEHQAAYGn/Hxsqz+pN4I7rAAAAAElFTkSuQmCC\n"
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data['family']=data['Parch']+data['SibSp']\n",
        "data"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 423
        },
        "id": "GBaHyr7Y5Hns",
        "outputId": "929492d0-fc79-4412-9ce7-1103b9a40707"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "     PassengerId  Survived  Pclass  Sex  ...  Parch     Fare  Embarked  family\n",
              "0              1         0       3    1  ...      0   7.2500         2       1\n",
              "1              2         1       1    0  ...      0  71.2833         0       1\n",
              "2              3         1       3    0  ...      0   7.9250         2       0\n",
              "3              4         1       1    0  ...      0  53.1000         2       1\n",
              "4              5         0       3    1  ...      0   8.0500         2       0\n",
              "..           ...       ...     ...  ...  ...    ...      ...       ...     ...\n",
              "886          887         0       2    1  ...      0  13.0000         2       0\n",
              "887          888         1       1    0  ...      0  30.0000         2       0\n",
              "888          889         0       3    0  ...      2  23.4500         2       3\n",
              "889          890         1       1    1  ...      0  30.0000         0       0\n",
              "890          891         0       3    1  ...      0   7.7500         1       0\n",
              "\n",
              "[891 rows x 10 columns]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-a681bd2e-1ce7-4690-a82e-e59802f3da78\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>PassengerId</th>\n",
              "      <th>Survived</th>\n",
              "      <th>Pclass</th>\n",
              "      <th>Sex</th>\n",
              "      <th>Age</th>\n",
              "      <th>SibSp</th>\n",
              "      <th>Parch</th>\n",
              "      <th>Fare</th>\n",
              "      <th>Embarked</th>\n",
              "      <th>family</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>22.0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>7.2500</td>\n",
              "      <td>2</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>2</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>38.0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>71.2833</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>3</td>\n",
              "      <td>0</td>\n",
              "      <td>26.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>7.9250</td>\n",
              "      <td>2</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>4</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>35.0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>53.1000</td>\n",
              "      <td>2</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>5</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>35.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>8.0500</td>\n",
              "      <td>2</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>886</th>\n",
              "      <td>887</td>\n",
              "      <td>0</td>\n",
              "      <td>2</td>\n",
              "      <td>1</td>\n",
              "      <td>27.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>13.0000</td>\n",
              "      <td>2</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>887</th>\n",
              "      <td>888</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>19.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>30.0000</td>\n",
              "      <td>2</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>888</th>\n",
              "      <td>889</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>0</td>\n",
              "      <td>28.0</td>\n",
              "      <td>1</td>\n",
              "      <td>2</td>\n",
              "      <td>23.4500</td>\n",
              "      <td>2</td>\n",
              "      <td>3</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>889</th>\n",
              "      <td>890</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>26.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>30.0000</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>890</th>\n",
              "      <td>891</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>32.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>7.7500</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>891 rows × 10 columns</p>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-a681bd2e-1ce7-4690-a82e-e59802f3da78')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-a681bd2e-1ce7-4690-a82e-e59802f3da78 button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-a681bd2e-1ce7-4690-a82e-e59802f3da78');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ]
          },
          "metadata": {},
          "execution_count": 134
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data.drop(['Fare','SibSp','Parch'],axis=1)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 423
        },
        "id": "_jYilwx19dL4",
        "outputId": "6bc26e25-3cf9-4a0d-90d7-e3b19c88741b"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "     PassengerId  Survived  Pclass  Sex   Age  Embarked  family\n",
              "0              1         0       3    1  22.0         2       1\n",
              "1              2         1       1    0  38.0         0       1\n",
              "2              3         1       3    0  26.0         2       0\n",
              "3              4         1       1    0  35.0         2       1\n",
              "4              5         0       3    1  35.0         2       0\n",
              "..           ...       ...     ...  ...   ...       ...     ...\n",
              "886          887         0       2    1  27.0         2       0\n",
              "887          888         1       1    0  19.0         2       0\n",
              "888          889         0       3    0  28.0         2       3\n",
              "889          890         1       1    1  26.0         0       0\n",
              "890          891         0       3    1  32.0         1       0\n",
              "\n",
              "[891 rows x 7 columns]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-f02ba3b5-eac8-4b44-83b1-5bc7dac81ddd\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>PassengerId</th>\n",
              "      <th>Survived</th>\n",
              "      <th>Pclass</th>\n",
              "      <th>Sex</th>\n",
              "      <th>Age</th>\n",
              "      <th>Embarked</th>\n",
              "      <th>family</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>22.0</td>\n",
              "      <td>2</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>2</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>38.0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>3</td>\n",
              "      <td>0</td>\n",
              "      <td>26.0</td>\n",
              "      <td>2</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>4</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>35.0</td>\n",
              "      <td>2</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>5</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>35.0</td>\n",
              "      <td>2</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>886</th>\n",
              "      <td>887</td>\n",
              "      <td>0</td>\n",
              "      <td>2</td>\n",
              "      <td>1</td>\n",
              "      <td>27.0</td>\n",
              "      <td>2</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>887</th>\n",
              "      <td>888</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>19.0</td>\n",
              "      <td>2</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>888</th>\n",
              "      <td>889</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>0</td>\n",
              "      <td>28.0</td>\n",
              "      <td>2</td>\n",
              "      <td>3</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>889</th>\n",
              "      <td>890</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>26.0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>890</th>\n",
              "      <td>891</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>32.0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>891 rows × 7 columns</p>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-f02ba3b5-eac8-4b44-83b1-5bc7dac81ddd')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-f02ba3b5-eac8-4b44-83b1-5bc7dac81ddd button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-f02ba3b5-eac8-4b44-83b1-5bc7dac81ddd');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ]
          },
          "metadata": {},
          "execution_count": 135
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "x=data.drop(['Survived'],axis=1).values\n",
        "y=data['Survived'].values"
      ],
      "metadata": {
        "id": "RhKANNGK-QLk"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.model_selection import train_test_split\n",
        "x_train,x_test,y_train,y_test=train_test_split(x,y)"
      ],
      "metadata": {
        "id": "Xc0VTxG_-lx4"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from sklearn.metrics import accuracy_score\n",
        "i=LogisticRegression()\n",
        "i.fit(x_train, y_train)\n",
        "ir=i.predict(x_test)\n",
        "accuracy_score(y_test,ir)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "cmCDL9wU_vkr",
        "outputId": "d9d7b213-27a1-45f5-967d-c9163f8c4a46"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
            "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
            "\n",
            "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
            "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
            "Please also refer to the documentation for alternative solver options:\n",
            "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
            "  n_iter_i = _check_optimize_result(\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "0.8071748878923767"
            ]
          },
          "metadata": {},
          "execution_count": 151
        }
      ]
    }
  ]
}